[general]
import = ["~/.config/alacritty/themes/iterm.toml"]

[font]
# size = 10
size = 11
# size = 12
# size = 13

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
opacity = 0.95
dynamic_title = true

[window.padding]
x = 4
y = 4
