theme = "bogster"
# theme = "vim-dark-contrast"
# theme = "amberwood"
# theme = "autumn"

[editor]
# bufferline = "multiple"
bufferline = "never"
line-number = "relative"
cursorline = true
color-modes = true
auto-pairs = true
auto-format = false
rulers = [80]
mouse = false
scrolloff = 10

[editor.auto-save]
focus-lost = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "file-type"]
center = ["version-control"]
right = ["diagnostics", "primary-selection-length", "selections", "register", "position", "file-encoding"]
separator = "â”‚"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.indent-guides]
render = true
character = "|"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = false

[keys.insert]
j = { k = "normal_mode" }

[keys.normal.space]
v = ":reload"
V = ":reload-all"
l = ":lsp-restart"
